sqlplus /nolog @cre_group 	PROM_100
sqlplus /nolog @cre_group 	PROM_101
sqlplus /nolog @cre_group 	PROM_102
sqlplus /nolog @cre_group 	PROM_103
sqlplus /nolog @cre_group 	PROM_104
sqlplus /nolog @cre_group 	PROM_105
sqlplus /nolog @cre_group 	PROM_106
sqlplus /nolog @cre_group 	PROM_107
sqlplus /nolog @cre_group 	PROM_109
sqlplus /nolog @cre_group 	PROM_110
sqlplus /nolog @cre_group 	PROM_111
sqlplus /nolog @cre_group 	PROM_112
sqlplus /nolog @cre_group 	PROM_113
sqlplus /nolog @cre_group 	PROM_114
sqlplus /nolog @cre_group 	PROM_115
sqlplus /nolog @cre_group 	PROM_116
sqlplus /nolog @cre_group 	PROM_117
sqlplus /nolog @cre_group 	PROM_118
sqlplus /nolog @cre_group 	PROM_120
sqlplus /nolog @cre_group 	PROM_121
sqlplus /nolog @cre_group 	PROM_122
sqlplus /nolog @cre_group 	PROM_123
sqlplus /nolog @cre_group 	PROM_124
sqlplus /nolog @cre_group 	PROM_125
sqlplus /nolog @cre_group 	PROM_126
sqlplus /nolog @cre_group 	PROM_128
sqlplus /nolog @cre_group 	PROM_129
sqlplus /nolog @cre_group 	PROM_130
sqlplus /nolog @cre_group 	PROM_131
sqlplus /nolog @cre_group 	PROM_132
sqlplus /nolog @cre_group 	PROM_133
sqlplus /nolog @cre_group 	PROM_134
sqlplus /nolog @cre_group 	PROM_135
sqlplus /nolog @cre_group 	PROM_136
sqlplus /nolog @cre_group 	PROM_138
sqlplus /nolog @cre_group 	PROM_140
sqlplus /nolog @cre_group 	PROM_141
sqlplus /nolog @cre_group 	PROM_142
sqlplus /nolog @cre_group 	PROM_143
sqlplus /nolog @cre_group 	PROM_146
sqlplus /nolog @cre_group 	PROM_147
sqlplus /nolog @cre_group 	PROM_149
sqlplus /nolog @cre_group 	PROM_150
sqlplus /nolog @cre_group 	PROM_151
sqlplus /nolog @cre_group 	PROM_153
sqlplus /nolog @cre_group 	PROM_154
sqlplus /nolog @cre_group 	PROM_156
sqlplus /nolog @cre_group 	PROM_205
sqlplus /nolog @cre_group 	PROM_206
sqlplus /nolog @cre_group 	PROM_207
sqlplus /nolog @cre_group 	PROM_208
sqlplus /nolog @cre_group 	PROM_209
sqlplus /nolog @cre_group 	PROM_210
sqlplus /nolog @cre_group 	PROM_212
sqlplus /nolog @cre_group 	PROM_213
sqlplus /nolog @cre_group 	PROM_214
sqlplus /nolog @cre_group 	PROM_215
sqlplus /nolog @cre_group 	PROM_216
sqlplus /nolog @cre_group 	PROM_217
sqlplus /nolog @cre_group 	PROM_218
sqlplus /nolog @cre_group 	PROM_219
sqlplus /nolog @cre_group 	PROM_25
sqlplus /nolog @cre_group 	PROM_251
